import stripIndent from 'strip-indent';
import type { Plugin } from '../../plugin.js';

/**
 * Plugin that generates CMakeLists.txt for Android to link generated native code.
 *
 * This is the Android equivalent of the iOS CocoaPods integration.
 * It generates a CMakeLists.txt that the polygen library can include via add_subdirectory.
 */
export function androidCmake(): Plugin {
  return {
    name: 'core/android-cmake',
    title: 'Android CMake Integration',

    async hostProjectGenerated({ projectOutput }): Promise<void> {
      await projectOutput.writeAllTo({
        'CMakeLists.txt': buildCMakeListsSource(),
      });
    },
  };
}

/**
 * Builds the CMakeLists.txt for Android generated code.
 *
 * This CMakeLists.txt:
 * 1. Collects all generated C/C++ sources (loader.cpp, module files, wasm-rt runtime)
 * 2. Defines a static library target that can be linked into libpolygen.so
 * 3. Sets up include directories for the polygen library headers
 */
function buildCMakeListsSource(): string {
  return stripIndent(
    `
    # THIS FILE WAS GENERATED BY \`polygen\`
    # DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.

    cmake_minimum_required(VERSION 3.13)

    # Marker that this is polygen-generated code
    set(POLYGEN_GENERATED_HOST ON PARENT_SCOPE)

    # Collect all C++ sources from generated modules
    file(GLOB_RECURSE POLYGEN_GENERATED_CPP_SOURCES
      "\${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
    )

    # Collect all C sources (wasm-rt runtime and generated module code)
    file(GLOB_RECURSE POLYGEN_GENERATED_C_SOURCES
      "\${CMAKE_CURRENT_SOURCE_DIR}/*.c"
    )

    # Create an object library for generated code
    # This allows the sources to be compiled and linked into libpolygen.so
    add_library(polygen_generated OBJECT
      \${POLYGEN_GENERATED_CPP_SOURCES}
      \${POLYGEN_GENERATED_C_SOURCES}
    )

    # Include directories:
    # - CMAKE_CURRENT_SOURCE_DIR: the generated code root (for loader.cpp, imports, etc.)
    # - wasm-rt: the wasm-rt runtime headers (wasm-rt.h, etc.)
    # - POLYGEN_INCLUDE_DIR: the polygen library headers (set by parent CMakeLists.txt)
    # - POLYGEN_INCLUDE_DIR/ReactNativePolygen: for StaticLibraryModule.h, etc.
    # - POLYGEN_INCLUDE_DIR/ReactNativePolygen/WebAssembly: for Module.h (included by StaticLibraryModule.h)
    target_include_directories(polygen_generated PRIVATE
      \${CMAKE_CURRENT_SOURCE_DIR}
      \${CMAKE_CURRENT_SOURCE_DIR}/wasm-rt
      \${POLYGEN_INCLUDE_DIR}
      \${POLYGEN_INCLUDE_DIR}/ReactNativePolygen
      \${POLYGEN_INCLUDE_DIR}/ReactNativePolygen/WebAssembly
    )

    # Link against ReactAndroid::jsi to get JSI headers
    # This is found via prefab in the parent CMakeLists.txt
    find_package(ReactAndroid REQUIRED CONFIG)
    target_link_libraries(polygen_generated PRIVATE ReactAndroid::jsi)

    # Compiler flags matching polygen library
    target_compile_options(polygen_generated PRIVATE
      -fexceptions
      -frtti
      -O2
      -fstack-protector-all
    )
    `
  ).trimStart();
}
